### ISSUE TITLE
Change state of button "Add to Project"

### ISSUE THREAD

**Issue by grooleivsgard** [SquareRoot-As/SquareRoot#28]
## Description
On shop/shop-detail, the button Add to Project should add the current plant/concept to a project. When this is added to a project, the button should change to "Remove from Project", with the following styling:

 <Button color="error" startIcon={<FeatherIcon icon="trash" width="18" height="18" />}>Remove from Project</Button>

<img width="1057" alt="bilde" src="https://user-images.githubusercontent.com/77729945/139683891-0cf18f3a-e18c-45a1-9575-de64fadebed5.png">

## Subissues

Issue #27 is related to this, as this will directly affect the state of the button. 

## Correct issue checklist:

- [x] I have added a detailed description
- [x] I have assigned a Description label (enhancement / bug / etc.)
- [x] I have assigned a contributor
- [x] I have added a Milestone (if applicable)
